### ISSUE TITLE
Can you provide the requirement.txt  for FedX to run

### ISSUE THREAD

**Issue by zhangyi-820** [Sungwon-Han/FEDX#4]
Hello, I am trying to run FedX locally, but I seem to have encountered some package incompatibility issues. Can you provide me with the necessary environment information for FedX to run? If you could provide the requirements.  Thanks

**Comment by Sungwon-Han** [comment]
Sorry for the late response. Here below the requirements to run the FedX.

python=3.8.0
torch=1.10.1
torchvision=0.11.2
numpy=1.24.4

Please let me know if you have problems running the code with these requirements!
